controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


products_details:
    path: '/produits/{slug}'
    controller: App\Controller\ProductsController::details

profile_index:
    path: '/profil/{id}'
    controller: App\Controller\ProfileController::index